/*
Lee and Elsa are brother and sister and are playing building block games together. Lee and Elsa are trying to construct a pyramid shape using building blocks. The pyramid is constructed by generating prime numbers between two years. The total number of blocks in each row is increased by two to construct a pyramid. The first row of the pyramid always has only one block. Lee and Elsa need a sufficient number of blocks to construct every row if they have an insufficient number of blocks, hence they cannot construct a row. Each block is numbered with the digit ‘BEE’. Digit ‘BEE’ in a block is generated by adding digits in a prime number. Row with the largest number of blocks kept at the bottom of the pyramid and the second largest number of blocks in a row will be kept above the bottom row and it continues up to the first row. Help Lee and Elsa to construct the pyramid.

Input format
The first line of the input consists of an integer – N representing year 1.
The second line of the input consists of an integer – M representing year 2.

Constraints
1 ≤ N ≤ 105
1 ≤ M ≤ 105

Example Input 1:
    20 
    200 

Output 1:
					5					
				2	4	1				
			5	7	2	8	5			
		7	4	8	1	7	2	8		
	7	2	4	8	1	5	1	5	2	
4	5	7	4	1	5	2	8	1	2	4

Explanation: 
    Prime year are between year 1 and year 2 are given below.
23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199. Six row of pyramid can be generated.
	First row sum of digits in the first prime number is written in the first row.
	Second row next three prime numbers are taken and the sum of digits is 2, 4, 1
	Third row next five prime numbers are taken and the sum of digits is 5,7,2,8,5
To construct the seventh row only two prime numbers are available, hence the pyramid has only 6 rows.




Example Input 2:
    2000
    2100

Ouput 2:
		5		
	5	1	2	
4	5	1	9	8

Explanation: 
    Prime year are between year 1 and year 2 are given below.
2003,2011,2017,2027,2029,2039,2053,2063,2069,2081,2083,2087,2089,2099
Three rows of the pyramid were constructed from 2003 to 2069.  There are no sufficient number of prime years to construct fourth row

*/

#include <stdio.h>
#include <stdbool.h>

bool isPrime(int year) {
    if (year <= 1)
        return false;
    for (int i = 2; i * i <= year; i++) {
        if (year % i == 0)
            return false;
    }
    return true;
}

void generatePrimes(int start, int end, int primes[], int *numPrimes) {
    *numPrimes = 0;
    for (int year = start; year <= end; year++) {
        if (isPrime(year)) {
            primes[*numPrimes] = year;
            (*numPrimes)++;
        }
    }
}

void generatePyramid(int primes[], int numPrimes) {
    int numRows = numPrimes;
    int maxBlocks = primes[numPrimes - 1];
    int pyramid[numRows][maxBlocks];
    for (int i = 0; i < numRows; i++) {
        int currentYear = primes[i];
        int sumOfDigits = 0;
        while (currentYear != 0) {
            sumOfDigits += currentYear % 10;
            currentYear /= 10;
        }
        int blocks = sumOfDigits;
        int spaces = maxBlocks - blocks;
        for (int j = 0; j < spaces; j++)
            printf("\t");
        for (int j = 0; j < blocks; j++) {
            if (j == 0)
                printf("%d", sumOfDigits);
            else
                printf("\t%d", sumOfDigits);
        }
        printf("\n");
    }
}

int main() {
    int startYear, endYear;
    scanf("%d%d", &startYear, &endYear);
    
    int primes[100000]; 
    int numPrimes;

    generatePrimes(startYear, endYear, primes, &numPrimes);
    generatePyramid(primes, numPrimes);

    return 0;
}
